# Configure JSON-RPC method services.
services:
  jsonrpc.method.a:
    class: DemoApp\Method\MethodA
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodA' }

  ## Resolver mock
  resolver:
    class: DemoApp\Resolver\JsonRpcMethodResolver
    tags: ['json_rpc_http_server.method_aware']


  # Alias resolver mock to bundle resolver
  json_rpc_http_server.alias.method_resolver: '@resolver'

  # MethodDocCreated Listener
  server_doc_created.listener:
    class: DemoApp\Listener\ServerDocCreatedListener
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_http_server_doc.server_doc_created'
        method: 'enhanceServerDoc'
