# Configure JSON-RPC method services.
services:
  jsonrpc.method.a:
    class: DemoApp\Method\MethodA
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodA' }
  jsonrpc.method.b:
    class: DemoApp\Method\MethodB
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodB' }

  # MethodDocCreated Listener
  method_doc_created.listener:
    class: DemoApp\Listener\MethodDocCreatedListener
    tags:
      - name: 'kernel.event_listener'
        event: 'json_rpc_http_server_doc.method_doc_created'
        method: 'enhanceMethodDoc'
